// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"MadeWithMv","status":true,"description":"メイン画面へ進む前に、\"Made with MV\"のスプラッシュ画面もしくはカスタマイズされたスプラッシュ画面を表示します。","parameters":{"Show Made With MV":"false","Made with MV Image":"MadeWithMv","Show Custom Splash":"false","Custom Image":"","Fade Out Time":"20","Fade In Time":"20","Wait Time":"5"}},
{"name":"HzRandomChoice","status":true,"description":"選択肢の順番をランダムにします。また、タイマーが0になった際に強制的に最後の選択肢を選択させます。","parameters":{}},
{"name":"DTextPicture","status":true,"description":"動的文字列ピクチャ生成プラグイン","parameters":{}},
{"name":"ControlVariable","status":true,"description":"変数の操作","parameters":{}},
{"name":"MKR_PlayerMoveForbid","status":true,"description":"(v1.0.1) 指定された番号のスイッチがONの間、\nプレイヤー操作によるキャラの移動を禁止します。","parameters":{"Default_Move_Flag":"10"}}
];
